name: nereye_gitmeli_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartx: any
  intl: ^0.17.0
  fluttertoast: ^7.1.6
  url_launcher: ^6.0.3
  dart_ipify: ^1.0.2
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^1.0.7
  sqflite: ^1.3.0
  path: ^1.8.0
  shared_preferences: ^2.0.5
  http: ^0.13.2
  cloud_firestore_web: ^1.0.7
  path_provider: ^2.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Yurtici/
    - assets/images/Yurtdisi/
    - assets/images/Background/
    - assets/images/Yurtici/Mekan/Ankara/
    - assets/images/Yurtici/Mekan/Antalya/
    - assets/images/Yurtici/Mekan/Aydın/
    - assets/images/Yurtici/Mekan/Bolu/
    - assets/images/Yurtici/Mekan/Bursa/
    - assets/images/Yurtici/Mekan/Denizli/
    - assets/images/Yurtici/Mekan/Edirne/
    - assets/images/Yurtici/Mekan/Eskişehir/
    - assets/images/Yurtici/Mekan/Muğla/
    - assets/images/Yurtici/Yemek/Ankara/
    - assets/images/Yurtici/Yemek/Antalya/
    - assets/images/Yurtici/Yemek/Aydın/
    - assets/images/Yurtici/Yemek/Bolu/
    - assets/images/Yurtici/Yemek/Bursa/
    - assets/images/Yurtici/Yemek/Denizli/
    - assets/images/Yurtici/Yemek/Edirne/
    - assets/images/Yurtici/Yemek/Eskişehir/
    - assets/images/Yurtici/Yemek/Muğla/
    - assets/images/Yurtdisi/Mekan/Cambridge/
    - assets/images/Yurtdisi/Mekan/Los Angeles/
    - assets/images/Yurtdisi/Mekan/Londra/
    - assets/images/Yurtdisi/Mekan/Toronto/
    - assets/images/Yurtdisi/Yemek/Cambridge/
    - assets/images/Yurtdisi/Yemek/Los Angeles/
    - assets/images/Yurtdisi/Yemek/Londra/
    - assets/images/Yurtdisi/Yemek/Toronto/
    - assets/images/App/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
